#!/usr/bin/env python3

import sys
from protocol.handler import ProtocolHandler


def main() -> None:
    handler = ProtocolHandler()

    while True:
        try:
            line = input().strip()
        except EOFError:
            break
        if not line:
            continue

        if line.upper() == "BOARD":
            board_lines = []
            while True:
                try:
                    board_line = input().strip()
                    if board_line.upper() == "DONE":
                        break
                    if board_line:
                        board_lines.append(board_line)
                except EOFError:
                    break
            response = handler.handle_board_lines(board_lines)
            if response:
                print(response, flush=True)
            continue

        response = handler.process(line)
        if response is not None:
            print(response, flush=True)

        if handler.should_exit:
            break


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)